// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PJATK_APBD_Cw4_s30734.Infrastructre;

#nullable disable

namespace PJATK_APBD_Cw4_s30734.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260520180610_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PJATK_APBD_Cw4_s30734.Models.ComponentManufacturers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INT",
                            FoundationDate = new DateOnly(1968, 7, 18),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateOnly(1969, 5, 1),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NVDA",
                            FoundationDate = new DateOnly(1993, 4, 5),
                            FullName = "Nvidia Corporation"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "ASUS",
                            FoundationDate = new DateOnly(1989, 4, 2),
                            FullName = "ASUSTeK Computer Inc."
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "MSI",
                            FoundationDate = new DateOnly(1986, 8, 4),
                            FullName = "Micro-Star International"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s30734.Models.ComponentTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentsTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "MB",
                            Name = "Motherboard"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "PSU",
                            Name = "Power Supply Unit"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s30734.Models.Components", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "COMP-00001",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "High-end CPU",
                            Name = "Intel Core i9-13900K"
                        },
                        new
                        {
                            Code = "COMP-00002",
                            ComponentManufacturersId = 2,
                            ComponentTypesId = 1,
                            Description = "High-end CPU",
                            Name = "AMD Ryzen 9 7950X"
                        },
                        new
                        {
                            Code = "COMP-00003",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 2,
                            Description = "High-end GPU",
                            Name = "Nvidia RTX 4090"
                        },
                        new
                        {
                            Code = "COMP-00004",
                            ComponentManufacturersId = 4,
                            ComponentTypesId = 3,
                            Description = "High-end Motherboard",
                            Name = "ASUS ROG MAXIMUS Z790 HERO"
                        },
                        new
                        {
                            Code = "COMP-00005",
                            ComponentManufacturersId = 5,
                            ComponentTypesId = 3,
                            Description = "Mid-range Motherboard",
                            Name = "MSI MPG B650 CARBON"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s30734.Models.PCComponents", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "COMP-00001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "COMP-00003",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "COMP-00002",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "COMP-00004",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 4,
                            ComponentCode = "COMP-00005",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s30734.Models.PCs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gamer Pro X",
                            Stock = 10,
                            Warranty = 24,
                            Weight = 15.5f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Workstation",
                            Stock = 50,
                            Warranty = 12,
                            Weight = 8.2f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Creator Studio 9000",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 18f
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget Gamer",
                            Stock = 20,
                            Warranty = 24,
                            Weight = 12.1f
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Home Media PC",
                            Stock = 15,
                            Warranty = 12,
                            Weight = 10f
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s30734.Models.Components", b =>
                {
                    b.HasOne("PJATK_APBD_Cw4_s30734.Models.ComponentManufacturers", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw4_s30734.Models.ComponentTypes", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s30734.Models.PCComponents", b =>
                {
                    b.HasOne("PJATK_APBD_Cw4_s30734.Models.Components", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw4_s30734.Models.PCs", "Pcs")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pcs");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s30734.Models.ComponentManufacturers", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s30734.Models.ComponentTypes", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s30734.Models.Components", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s30734.Models.PCs", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
